name: CI/CD Pipeline for Node.js

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        # run: npm test
        run: echo "No tests specified"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    # - name: Set up kubectl
    #   run: |
    #     echo "${{ secrets.KUBE_CONFIG_CONTENT }}" > kubeconfig
    #     export KUBECONFIG=kubeconfig

    - name: Deploy to EKS
      run: |
        kubectl apply -f kuubernetes/deployment.yaml --validate=false
        kubectl apply -f kuubernetes/deployment.yaml

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed."
